// Mocks generated by Mockito 5.4.5 from annotations
// in circle_share/test/features/category/presentation/view_model/category/category_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:circle_share/core/error/failure.dart' as _i6;
import 'package:circle_share/features/category/domain/entity/category_entity.dart'
    as _i8;
import 'package:circle_share/features/category/domain/repository/category_repository.dart'
    as _i2;
import 'package:circle_share/features/category/domain/use_case/add_category_usecase.dart'
    as _i4;
import 'package:circle_share/features/category/domain/use_case/delete_category_usecase.dart'
    as _i9;
import 'package:circle_share/features/category/domain/use_case/get_all_categories_usecase.dart'
    as _i7;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeICategoryRepository_0 extends _i1.SmartFake
    implements _i2.ICategoryRepository {
  _FakeICategoryRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AddCategoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddCategoryUseCase extends _i1.Mock
    implements _i4.AddCategoryUseCase {
  MockAddCategoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ICategoryRepository get categoryRepository => (super.noSuchMethod(
        Invocation.getter(#categoryRepository),
        returnValue: _FakeICategoryRepository_0(
          this,
          Invocation.getter(#categoryRepository),
        ),
      ) as _i2.ICategoryRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i4.AddCategoryParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [GetAllCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCategoriesUseCase extends _i1.Mock
    implements _i7.GetAllCategoriesUseCase {
  MockGetAllCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ICategoryRepository get categoryRepository => (super.noSuchMethod(
        Invocation.getter(#categoryRepository),
        returnValue: _FakeICategoryRepository_0(
          this,
          Invocation.getter(#categoryRepository),
        ),
      ) as _i2.ICategoryRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i8.CategoryEntity>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i8.CategoryEntity>>>.value(
                _FakeEither_1<_i6.Failure, List<_i8.CategoryEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i8.CategoryEntity>>>);
}

/// A class which mocks [DeleteCategoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteCategoryUseCase extends _i1.Mock
    implements _i9.DeleteCategoryUseCase {
  MockDeleteCategoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ICategoryRepository get categoryRepository => (super.noSuchMethod(
        Invocation.getter(#categoryRepository),
        returnValue: _FakeICategoryRepository_0(
          this,
          Invocation.getter(#categoryRepository),
        ),
      ) as _i2.ICategoryRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i9.DeleteCategoryParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
